// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package proto.user;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.user.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nick_name = 1;</code>
   * @return The nickName.
   */
  java.lang.String getNickName();
  /**
   * <code>string nick_name = 1;</code>
   * @return The bytes for nickName.
   */
  com.google.protobuf.ByteString
      getNickNameBytes();

  /**
   * <code>string sign = 2;</code>
   * @return The sign.
   */
  java.lang.String getSign();
  /**
   * <code>string sign = 2;</code>
   * @return The bytes for sign.
   */
  com.google.protobuf.ByteString
      getSignBytes();

  /**
   * <code>string age = 3;</code>
   * @return The age.
   */
  java.lang.String getAge();
  /**
   * <code>string age = 3;</code>
   * @return The bytes for age.
   */
  com.google.protobuf.ByteString
      getAgeBytes();
}
