// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package proto.user;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_user_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_user_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_user_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_user_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\nproto.user\"T\n\013UserRequest\022" +
      "\014\n\004uuid\030\001 \001(\t\022\020\n\010username\030\002 \001(\t\022\020\n\010passw" +
      "ord\030\003 \001(\t\022\023\n\013permissions\030\004 \001(\t\"<\n\014UserRe" +
      "sponse\022\021\n\tnick_name\030\001 \001(\t\022\014\n\004sign\030\002 \001(\t\022" +
      "\013\n\003age\030\003 \001(\tB\031\n\nproto.userB\tUserProtoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_user_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_user_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_user_UserRequest_descriptor,
        new java.lang.String[] { "Uuid", "Username", "Password", "Permissions", });
    internal_static_proto_user_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_user_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_user_UserResponse_descriptor,
        new java.lang.String[] { "NickName", "Sign", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
