// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package proto.user;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.user.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <pre>
   *权限
   * </pre>
   *
   * <code>string permissions = 4;</code>
   * @return The permissions.
   */
  java.lang.String getPermissions();
  /**
   * <pre>
   *权限
   * </pre>
   *
   * <code>string permissions = 4;</code>
   * @return The bytes for permissions.
   */
  com.google.protobuf.ByteString
      getPermissionsBytes();
}
